// Web Push (VAPID + aes128gcm), adapted from nuojiji-relay (MIT)
const enc=new TextEncoder();
function b64urlToBytes(s){const b=s.replace(/-/g,'+').replace(/_/g,'/'),p=b+'='.repeat((4-b.length%4)%4),x=atob(p),o=new Uint8Array(x.length);for(let i=0;i<x.length;i++)o[i]=x.charCodeAt(i);return o}
function bytesToB64url(bytes){let x='',b=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);for(let i=0;i<b.length;i++)x+=String.fromCharCode(b[i]);return btoa(x).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function cat(...a){const n=a.reduce((s,x)=>s+x.length,0),o=new Uint8Array(n);let p=0;for(const x of a){o.set(x,p);p+=x.length}return o}
const VK='vapid:keys';
async function gen(){const p=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign']),pub=new Uint8Array(await crypto.subtle.exportKey('raw',p.publicKey)),j=await crypto.subtle.exportKey('jwk',p.privateKey);return{pub:bytesToB64url(pub),priv:j.d}}
async function vapid(env){if(env.VAPID_PUBLIC_KEY&&env.VAPID_PRIVATE_KEY)return{pub:env.VAPID_PUBLIC_KEY,priv:env.VAPID_PRIVATE_KEY,subject:env.VAPID_SUBJECT||'mailto:relay@example.com'};let raw=await env.OUTBOX.get(VK);if(raw){try{const k=JSON.parse(raw);if(k.pub&&k.priv)return{...k,subject:env.VAPID_SUBJECT||'mailto:relay@example.com'}}catch{}}const k=await gen();await env.OUTBOX.put(VK,JSON.stringify(k));return{...k,subject:env.VAPID_SUBJECT||'mailto:relay@example.com'}}
export async function getVapidPublicKey(env){return(await vapid(env)).pub}
async function importKey(pubB64,privB64){const p=b64urlToBytes(pubB64),d=b64urlToBytes(privB64),x=bytesToB64url(p.slice(1,33)),y=bytesToB64url(p.slice(33,65));return crypto.subtle.importKey('jwk',{kty:'EC',crv:'P-256',x,y,d:bytesToB64url(d),ext:true},{name:'ECDSA',namedCurve:'P-256'},false,['sign'])}
async function jwt(endpoint,v){const u=new URL(endpoint),aud=`${u.protocol}//${u.host}`,h=bytesToB64url(enc.encode(JSON.stringify({typ:'JWT',alg:'ES256'}))),p=bytesToB64url(enc.encode(JSON.stringify({aud,exp:Math.floor(Date.now()/1000)+43200,sub:v.subject}))),input=`${h}.${p}`,k=await importKey(v.pub,v.priv),sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},k,enc.encode(input));return`${input}.${bytesToB64url(new Uint8Array(sig))}`}
async function hkdf(salt,ikm,info,len){const k=await crypto.subtle.importKey('raw',ikm,'HKDF',false,['deriveBits']),b=await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt,info},k,len*8);return new Uint8Array(b)}
async function encrypt(plain,sub){const ua=b64urlToBytes(sub.keys.p256dh),auth=b64urlToBytes(sub.keys.auth),lp=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),lpub=new Uint8Array(await crypto.subtle.exportKey('raw',lp.publicKey)),uak=await crypto.subtle.importKey('raw',ua,{name:'ECDH',namedCurve:'P-256'},false,[]),shared=new Uint8Array(await crypto.subtle.deriveBits({name:'ECDH',public:uak},lp.privateKey,256)),salt=crypto.getRandomValues(new Uint8Array(16)),ikm=await hkdf(auth,shared,cat(enc.encode('WebPush: info\0'),ua,lpub),32),cek=await hkdf(salt,ikm,enc.encode('Content-Encoding: aes128gcm\0'),16),nonce=await hkdf(salt,ikm,enc.encode('Content-Encoding: nonce\0'),12),ak=await crypto.subtle.importKey('raw',cek,{name:'AES-GCM'},false,['encrypt']),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce},ak,cat(plain,new Uint8Array([2]))));return cat(salt,new Uint8Array([0,0,16,0]),new Uint8Array([lpub.length]),lpub,ct)}
export async function sendWebPush(env,subscription,payload){const v=await vapid(env);if(!subscription?.endpoint||!subscription?.keys?.p256dh||!subscription?.keys?.auth)return{ok:false,gone:true};try{const body=await encrypt(enc.encode(JSON.stringify(payload)),subscription),token=await jwt(subscription.endpoint,v),r=await fetch(subscription.endpoint,{method:'POST',headers:{Authorization:`vapid t=${token}, k=${v.pub}`,'Content-Encoding':'aes128gcm','Content-Type':'application/octet-stream',TTL:'60'},body});if(r.status===200||r.status===201)return{ok:true,gone:false};if(r.status===404||r.status===410||(r.status>=400&&r.status<500&&r.status!==429))return{ok:false,gone:true,reason:String(r.status)};return{ok:false,gone:false,reason:String(r.status)}}catch(e){return{ok:false,gone:false,reason:String(e?.message||e)}}}
