import { getVapidPublicKey, sendWebPush } from './webPush.js';
const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8','access-control-allow-origin':'*'}});
const cors={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'Authorization,Content-Type'};
const auth=(r,e)=>{const h=r.headers.get('authorization')||'';return !!e.RELAY_SECRET&&h===`Bearer ${e.RELAY_SECRET}`};
const key=(i,c)=>`proactive:${i}:${c}`, outKey=i=>`outbox:${i}`, subKey=i=>`subs:${i}`;
const rand=(a,b)=>Math.round(a+Math.random()*(b-a));
async function readJson(kv,k,d){try{const v=await kv.get(k);return v?JSON.parse(v):d}catch{return d}}
async function writeJson(kv,k,v){await kv.put(k,JSON.stringify(v))}
async function addIndex(kv,k){const a=await readJson(kv,'proactive:index',[]);if(!a.includes(k)){a.push(k);await writeJson(kv,'proactive:index',a)}}
async function delIndex(kv,k){const a=(await readJson(kv,'proactive:index',[])).filter(x=>x!==k);await writeJson(kv,'proactive:index',a)}
async function addOutbox(kv,inbox,item){let a=await readJson(kv,outKey(inbox),[]);a.push(item);a=a.slice(-80);await writeJson(kv,outKey(inbox),a)}
async function pushAll(env,inbox,payload){const subs=await readJson(env.OUTBOX,subKey(inbox),[]),keep=[];for(const s of subs){const r=await sendWebPush(env,s,payload);if(!r.gone)keep.push(s)}if(keep.length!==subs.length)await writeJson(env.OUTBOX,subKey(inbox),keep)}
async function tick(env){const kv=env.OUTBOX,idx=await readJson(kv,'proactive:index',[]),now=Date.now();for(const k of idx){const c=await readJson(kv,k,null);if(!c||!c.enabled||!Array.isArray(c.cardPool)||!c.cardPool.length)continue;if(!c.nextDueAt||now<c.nextDueAt)continue;const choices=c.cardPool.filter(x=>x&&x!==c.lastText),text=(choices.length?choices:c.cardPool)[Math.floor(Math.random()*(choices.length?choices:c.cardPool).length)];if(!text)continue;const id=`relay_proactive_${c.charId}_${now}_${Math.random().toString(36).slice(2,7)}`;await addOutbox(kv,c.inboxId,{id,charId:c.charId,text,createdAt:now,proactive:true});c.lastText=text;c.lastFiredAt=now;c.nextDueAt=now+rand(c.intervalMin,c.intervalMax)*60000;await writeJson(kv,k,c);await pushAll(env,c.inboxId,{title:c.charName||'苜蓿',body:text,tag:`muxu-msg-${id}`,data:{messageId:id,charId:c.charId,conversationId:c.charId},kind:'relay-proactive'}).catch(()=>{})}}
export default {async fetch(request,env){const u=new URL(request.url),p=u.pathname;if(request.method==='OPTIONS')return new Response(null,{headers:cors});if(p==='/health')return J({ok:true,mode:'nuojiji-style-proactive-relay'});if(p==='/api/push/vapid-key'){return J({publicKey:await getVapidPublicKey(env)})}if(!auth(request,env))return J({error:'unauthorized'},401);if(p==='/api/push/subscribe'&&request.method==='POST'){const b=await request.json(),i=b.inboxId,s=b.subscription;if(!i||!s?.endpoint)return J({error:'inboxId / subscription required'},400);let a=await readJson(env.OUTBOX,subKey(i),[]);a=a.filter(x=>x.endpoint!==s.endpoint);a.push(s);await writeJson(env.OUTBOX,subKey(i),a.slice(-8));return J({ok:true})}if(p==='/proactive/register'&&request.method==='POST'){const b=await request.json(),{inboxId,userId,charId}=b;if(!inboxId||charId==null)return J({error:'inboxId / charId required'},400);const mn=Math.max(1,Math.min(1440,Number(b.intervalMin)||5)),mx=Math.max(mn,Math.min(1440,Number(b.intervalMax)||mn)),k=key(inboxId,String(charId)),old=await readJson(env.OUTBOX,k,null),changed=!old||old.intervalMin!==mn||old.intervalMax!==mx;const rec={...(old||{}),inboxId,userId:String(userId??'me'),charId:String(charId),charName:String(b.charName||'对方'),enabled:b.enabled!==false,intervalMin:mn,intervalMax:mx,cardPool:Array.isArray(b.cardPool)?[...new Set(b.cardPool.filter(x=>typeof x==='string'&&x.trim()).map(x=>x.trim()))].slice(0,300):[],updatedAt:Date.now()};if(!rec.nextDueAt||changed)rec.nextDueAt=Date.now()+rand(mn,mx)*60000;await writeJson(env.OUTBOX,k,rec);await addIndex(env.OUTBOX,k);return J({ok:true,nextDueAt:rec.nextDueAt})}if(p==='/proactive/unregister'&&request.method==='POST'){const b=await request.json(),k=key(b.inboxId,String(b.charId));await env.OUTBOX.delete(k);await delIndex(env.OUTBOX,k);return J({ok:true})}if(p==='/proactive/status'&&request.method==='GET'){const inbox=u.searchParams.get('inboxId'),idx=await readJson(env.OUTBOX,'proactive:index',[]),rows=[];for(const k of idx){const c=await readJson(env.OUTBOX,k,null);if(c&&c.inboxId===inbox)rows.push({charId:c.charId,enabled:c.enabled,nextDueAt:c.nextDueAt,lastFiredAt:c.lastFiredAt||0,intervalMin:c.intervalMin,intervalMax:c.intervalMax})}return J({pairs:rows})}if(p==='/outbox'&&request.method==='GET'){const i=u.searchParams.get('inboxId');if(!i)return J({error:'inboxId required'},400);return J({items:await readJson(env.OUTBOX,outKey(i),[]),now:Date.now()})}if(p==='/ack'&&request.method==='POST'){const b=await request.json(),ids=new Set(b.ids||[]),a=(await readJson(env.OUTBOX,outKey(b.inboxId),[])).filter(x=>!ids.has(x.id));await writeJson(env.OUTBOX,outKey(b.inboxId),a);return J({acked:ids.size})}return J({error:'not found'},404)},async scheduled(event,env,ctx){ctx.waitUntil(tick(env))}};
